import { ComponentProps } from "react";
export const SoundWave = (props: ComponentProps<"svg">) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={"100%"}
    height={32}
    fill="none"
    {...props}
  >
    <rect width={2} height={2} y={15} fill="#F9FAFB" opacity={0.66} rx={1} />
    <rect
      width={2}
      height={8}
      x={6}
      y={12}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={12}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={18}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={24}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={30}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={36}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={42}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={48}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={54}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={60}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={2}
      x={66}
      y={15}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={8}
      x={72}
      y={12}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={78}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={84}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={90}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={96}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={102}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={108}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={114}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={120}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={126}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={132}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={138}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={144}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={150}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={156}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={162}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={168}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={174}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={180}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={186}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={192}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={198}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={204}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={210}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={216}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={222}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={228}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={234}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={240}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={246}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={252}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={258}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={264}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={270}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={276}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={282}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={288}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={294}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={300}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={306}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={312}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={318}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={324}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={330}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={336}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={342}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={348}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={354}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={360}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={366}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={372}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={378}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={384}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={390}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={396}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={402}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={408}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={414}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={420}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={426}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={432}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={438}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={444}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={450}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={16}
      x={456}
      y={8}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={462}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={468}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={474}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={480}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={14}
      x={486}
      y={9}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={492}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={498}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={504}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={510}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={516}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={522}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={528}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={10}
      x={534}
      y={11}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={4}
      x={540}
      y={14}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
    <rect
      width={2}
      height={2}
      x={546}
      y={15}
      fill="#F9FAFB"
      opacity={0.66}
      rx={1}
    />
  </svg>
);
